version: '3.5'

services:
   backend:
      image: backend
      build:
         context: ./backend
         dockerfile: Dockerfile
      ports:
         - '8000:8000'
   frontend:
      image: frontend
      build:
         context: ./frontend
         dockerfile: Dockerfile
         args:
            BACKEND_URL: http://localhost:8000
      ports:
         - '3000:3000'
