export enum QueryKeys {
	SIGNIN_GITLAB = 'SIGNIN_GITLAB',
	USER = 'USER',
	AVATAR = 'AVATAR',
	AVATAR_ORIGINAL = 'AVATAR_ORIGINAL',
	COLLEAGUES = 'COLLEAGUES',
	FEEDBACK_LIST = 'FEEDBACK_LIST',
	FEEDBACK_LIST_EVENT = 'FEEDBACK_LIST_EVENT',
	FEEDBACK = 'FEEDBACK',
	EVENTS = 'EVENTS',
}
