export { default as AddColleaguesModal } from './AddColleaguesModal'
export { default as AddColleaguesModalView } from './AddColleaguesModalView'
export { default as ColleaguesTable } from './ColleaguesTable'
export { default as ColleaguesTableModal } from './ColleaguesTableModal'
export { default as ColleaguesTitle } from './ColleaguesTitle'
