export { default as createAvatar } from './createAvatar'
export { default as deleteAvatar } from './deleteAvatar'
export { default as getAvatarThumbnail } from './getAvatarThumbnail'
export { default as getOriginalAvatar } from './getOriginalAvatar'
export { default as getUser } from './getUser'
export { default as updateAvatarThumbnail } from './updateAvatarThumbnail'
